openapi: "3.0.2"
info:
  title: Tasks appliaction
  version: "0.0.1-SNAPSHOT"
  description: Simple CRUD application for keeping track of tasks
servers:
  - url: http://localhost:8080
    description: Local server

tags:
  - name: tasks
    description: Operations with tasks

paths:
  /tasks:
    get:
      description: Get all tasks
      tags:
        - tasks
      operationId: getTasks
      responses:
        "200":
          description: Array of tasks
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TaskRetrieve"
    post:
      description: Create a new task
      tags:
        - tasks
      operationId: createTask
      requestBody:
        required: true
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/TaskCreate"
      responses:
        "200":
          description: Created task
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/TaskRetrieve"

  /tasks/{id}:
    parameters:
      - $ref: "#/components/parameters/id"
    get:
      description: Get a task
      tags:
        - tasks
      operationId: getTask
      responses:
        "200":
          description: Task instance
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/TaskRetrieve"
    put:
      description: Update a task
      tags:
        - tasks
      operationId: updateTask
      responses:
        "200":
          description: Updated task
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/TaskRetrieve"
    delete:
      description: Delete a task
      tags:
        - tasks
      operationId: deleteTask
      responses:
        "204":
          description: Deleted

components:
  parameters:
    id:
      name: id
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/UUID"

  schemas:
    UUID:
      type: string
      format: uuid
    TaskRetrieve:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/UUID"
        name:
          type: string
        done:
          type: boolean
    TaskCreate:
      type: object
      properties:
        name:
          type: string
    TaskUpdate:
      properties:
        name:
          type: string
        done:
          type: boolean
